[Service]
ExecStart=
ExecStart=/usr/local/bin/ollama.bin serve
Environment=LD_LIBRARY_PATH=/opt/vgpu/lib:/usr/local/lib/ollama:/usr/local/lib/ollama/cuda_v12
Environment=LD_PRELOAD=/opt/vgpu/lib/libvgpu-nvml.so:/opt/vgpu/lib/libvgpu-cuda.so.1:/opt/vgpu/lib/libvgpu-cudart.so
Environment=OLLAMA_NUM_GPU=1
Environment=OLLAMA_LLM_LIBRARY=cuda_v12
Environment=OLLAMA_LIBRARY_PATH=/usr/local/lib/ollama:/usr/local/lib/ollama/cuda_v12
Environment=OLLAMA_DEBUG=DEBUG
