[Service]
Environment="LD_PRELOAD=/var/snap/ollama/common/lib/libcuda.so.1"
Environment="LD_LIBRARY_PATH=/var/snap/ollama/common/lib:/snap/ollama/105/lib/ollama:/snap/ollama/105/lib/ollama/cuda_v12"
Environment="OLLAMA_LIBRARY_PATH=/var/snap/ollama/common/lib:/snap/ollama/105/lib/ollama:/snap/ollama/105/lib/ollama/cuda_v12"
Environment="OLLAMA_LLM_LIBRARY=cuda_v12"
